install: go get -u github.com/jeshuam/jbuild && go install github.com/jeshuam/jbuild
script: find / 2&>1 | grep "clang++" #${GOPATH}/bin/jbuild --show_log --external_repo_dir=/tmp/build/external --base_workspace_files=${GOPATH}/src/github.com/jeshuam/jbuild/cfg run //:speed_test
language: generic
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.8
    packages:
      - clang-3.8
      - golang