compiler:
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install -y golang

install: go get -u github.com/jeshuam/jbuild && go install github.com/jeshuam/jbuild
script: ${GOPATH}/bin/jbuild --cc_compiler=clang++-3.8 --show_log --external_repo_dir=/tmp/build/external --base_workspace_files=${GOPATH}/src/github.com/jeshuam/jbuild/cfg run //:speed_test
language: c++
notifications:
  email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.8